### ISSUE TITLE
User Story: Login and run sign up

### ISSUE THREAD

**Issue by EMarnus** [EMarnus/love-running#3]
As a **signed up user** I can **Login** so that **I can RSVP/save upcoming events**

# Acceptance Criteria
- Acceptance Criteria 1: Have a sign-in page.
- Acceptance Criteria 2: Have a page that shows all upcoming events and lets you select which ones you want to go to.
- Acceptance Criteria 3: Have a section that shows all events that have been previously selected.
- Acceptance Criteria 4: Ability to remove selected events,
  
# Tasks
- [ ] Task 1: Create a Sign-In page or edit the Sign-Up page. 
- [ ] Task 2: Create backend for user sign-up and log-in.
- [ ] Task 3: Create an upcoming events page for signed-in users, needs to show all upcoming not just those on the main page.
- [ ] Task 4: Create backend admin function to add/edit events.
- [ ] Task 5: Create backend function that allows users to save events they are interested in
- [ ] Task 6: Create section for saved events.
